### ISSUE TITLE
How can I find example.mtx

### ISSUE THREAD

**Issue by puckbee** [bhSPARSE/Benchmark_SpMV_using_CSR5#2]
Should I generate a mtx file by myself, if I want to try your work?

**Comment by janecker** [comment]
It should be possible to use every matrix in mtx format. You can find many matrices at the matrix market website http://math.nist.gov/MatrixMarket/ or the florida sparse matrix collection http://www.cise.ufl.edu/research/sparse/matrices/list_by_id.html

**Comment by weifengliu-ssslab** [comment]
Many thanks Jan for answering the question!

Cheers,

Weifeng
