### ISSUE TITLE
Check... NO PASS! #Error on GPU k80c and Cuda 8.0

### ISSUE THREAD

**Issue by isratnisa** [bhSPARSE/Benchmark_SpMV_using_CSR5#6]
Hi,
I am trying to run CSR5 on a k80 machine. I am using Cuda-8.0 with compiler flag compute_60. Looks like it is running but not passing the test. Can you please have a look at this?

./spmv ../../../dataset/bcsstk33.mtx 
------------------------------------------------------
PRECISION = 32-bit Single Precision
------------------------------------------------------
--------------../../../dataset/bcsstk33.mtx--------------
 ( 8738, 8738 ) nnz = 591904
cpu sequential time = 1.32787 ms. Bandwidth = 5.40169 GB/s. GFlops = 0.891508 GFlops.

Device [0] Tesla K80,  @ 823.5MHz. 
omega = 32, sigma = 32. 
CSR->CSR5 malloc time = 0.566336 ms.
CSR->CSR5 tile_ptr time = 0.024704 ms.
CSR->CSR5 tile_desc time = 0.043552 ms.
CSR->CSR5 transpose time = 0.019552 ms.
CSR->CSR5 time = 0.851136 ms.
CSR5-based SpMV time = 0.00701181 ms. Bandwidth = 1022.95 GB/s. GFlops = 168.831 GFlops.
Check... NO PASS! #Error = 8738 out of 8738 entries.

**Comment by weifengliu-ssslab** [comment]
Hi Israt,

Thanks! The k80 card needs compute_37 to compile. Could you please try it then test the code?

Cheers,

Weifeng


________________________________

**Comment by isratnisa** [comment]
Thanks for your prompt reply.

As you already know, Cuda 8.0 has defined shfl_down(), atomic_add() etc. So I had to comment them out otherwise I was getting error that these functions are already defined. But If I comment out I get this:
detail/cuda/csr5_spmv_cuda.h(377): error: no instance of overloaded function "atomicAdd" matches the argument list.

Only if I use compute_60 I can compile without any error. I tried with compute_37. Same error as mentioned. Do I need to do something with the sm_* flag?

**Comment by isratnisa** [comment]
Hi,

I just noticed this problem is only for double precision. I think it's a common issue for double precision. I think I need to redefine the atomic_add(). Let me see. 

Thanks.

**Comment by weifengliu-ssslab** [comment]
Hi Israt,

Is everything fine about running the code for DP SpMV?

Weifeng

**Comment by isratnisa** [comment]
I never tried the DP version actually. Happy with the SP version. I think
you can close the issue.

**Comment by weifengliu-ssslab** [comment]
Got! Thanks to Israt!

Nice weekend!

Cheers,

Weifeng
